MVCApp/MVCApp/Models/ErrorViewModel.cs
namespace MVCApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MVCApp/MVCApp/Models/FormNumberInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVCApp.Models;

public class FormNumberInputModel
{
    public float CurrentNumber { get; set; }
    public string? SortType { get; set; }
}

MVCApp/MVCApp/Models/SortedDataModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace MVCApp.Models;
public class SortedDataModel
{
    [Key]
    public int Id { get; set; }
    
    public string? SortedNumberSequence { get; set; }

    public string? SortType { get; set; }

    public string? TimeElapsed { get; set; }
}

MVCApp/MVCApp/Controllers/NumberSequencesController.cs
using System.Diagnostics;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCApp.Data;
using MVCApp.Models;

namespace MVCApp.Controllers
{
    public class NumberSequencesController : Controller
    {
        private readonly MVCAppContext _context;

        public NumberSequencesController(MVCAppContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.Message = TempData["SubmissionMessage"] ?? "";
            return View();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (!_context.SortedDataModel.Any(x => x.Id == id))
            {
                return NotFound();
            }

            var sortedDataModel = await _context.SortedDataModel
                .FirstOrDefaultAsync(m => m.Id == id);
            
            if (sortedDataModel == null)
            {
                return NotFound();
            }
            
            return View(sortedDataModel);
        }
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                TempData["ErrorMessage"] = "Failed to delete sorted data";
            }

            var sortedData = await _context.SortedDataModel.FirstOrDefaultAsync(m => m.Id == id);
            if (sortedData == null)
            {
                TempData["ErrorMessage"] = "Failed to delete sorted data";
            }

            return View(sortedData);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sortedData = await _context.SortedDataModel.FindAsync(id);
            
            try
            {
                if (sortedData != null) _context.SortedDataModel.Remove(sortedData);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateException e)
            {
                Console.WriteLine(e);
                TempData["ErrorMessage"] = "Failed to delete sorted data";
            }
            
            return RedirectToAction(nameof(ViewSequences));
        }

        public async Task<IActionResult> ViewSequences()
        {
            ViewBag.Message = TempData["ErrorMessage"] ?? "";
            return View(await _context.SortedDataModel.ToListAsync());
        }

        [HttpGet("NumberSequences/ViewSequences/{sortType}")]
        public async Task<IActionResult> ViewSequences(string sortType, string searchString)
        {
            ViewBag.Message = TempData["ErrorMessage"] ?? "";
            ViewData["CurrentSort"] = sortType = String.IsNullOrEmpty(sortType) ? "Ascending" : sortType;
            ViewData["CurrentFilter"] = searchString;
            var sortedSequences = from s in _context.SortedDataModel
                select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                sortedSequences = sortedSequences.Where(x => x.SortedNumberSequence != null && x.SortedNumberSequence.Contains(searchString));
            }
            
            sortedSequences = sortType == "Ascending"
                ? sortedSequences.OrderBy(x => x.TimeElapsed)
                : sortedSequences.OrderByDescending(x => x.TimeElapsed);
            
            return View(await sortedSequences.AsNoTracking().ToListAsync());
        }

        public IActionResult SubmitNumber(float currentNumber)
        {
            int roundedToInt = (int)Math.Round(currentNumber);
            if (HttpContext.Request.Cookies.TryGetValue("NumberCookie", out var cookieValue))
            {
                HttpContext.Response.Cookies.Append("NumberCookie", cookieValue + "," + roundedToInt);
            }
            else
            {
                HttpContext.Response.Cookies.Append("NumberCookie", roundedToInt.ToString());
            }
            
            return RedirectToAction(nameof(Index));
        }
        
        [HttpPost]
        public async Task<IActionResult> SubmitAll(string sortType)
        {
            if (!HttpContext.Request.Cookies.TryGetValue("NumberCookie", out var cookieValue)) return RedirectToAction(nameof(Index));

            var numberSequence = cookieValue.Split(',', StringSplitOptions.RemoveEmptyEntries).Select(int.Parse).ToList();
            
            var watch = new Stopwatch();
        
            watch.Start();

            numberSequence = sortType == "Ascending" 
                ? numberSequence.OrderBy(x => x).ToList()
                : numberSequence.OrderByDescending(x => x).ToList();
        
            watch.Stop();

            var timeElapsed = watch.Elapsed.TotalMilliseconds + "ms";

            var numberSequenceText = string.Join(',',numberSequence);

            var sortedDataModel = new SortedDataModel
            {
                SortedNumberSequence = numberSequenceText,
                SortType = sortType,
                TimeElapsed = timeElapsed
            };

            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(sortedDataModel);
                    await _context.SaveChangesAsync();
                    TempData["SubmissionMessage"] = "Submission Successful";
                }
            }
            catch (DbUpdateException e)
            {
                Console.WriteLine(e);
                TempData["SubmissionMessage"] = "Submission failed";
            }

            HttpContext.Response.Cookies.Delete("NumberCookie");
            
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ExportAllSequences()
        {
            if (!_context.SortedDataModel.Any()) 
            {
                TempData["ErrorMessage"] = "No data to export";
                return RedirectToAction(nameof(ViewSequences));
            }
   
            const string fileName = "NumberSequences.json";
            const string mimeType = "application/json";
            await using var createStream = System.IO.File.Create(fileName);
            
            var sortedDataModels = await _context.SortedDataModel.ToListAsync();
            var jsonSerializerOptions = new JsonSerializerOptions { WriteIndented = true };
            var jsonString = JsonSerializer.Serialize(sortedDataModels, jsonSerializerOptions);
            
            var fileBytes = Encoding.UTF8.GetBytes(jsonString);
            
            return new FileContentResult(fileBytes, mimeType)
            {
                FileDownloadName = fileName
            };
        }
    }
}

MVCApp/MVCApp/Views/NumberSequences/Delete.cshtml
@model MVCApp.Models.SortedDataModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<div>
    <h4>SortedDataModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SortedNumberSequence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SortedNumberSequence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SortType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SortType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeElapsed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeElapsed)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ViewSequences">Back to List</a>
    </form>
</div>

MVCApp/MVCApp/Views/NumberSequences/Details.cshtml
@model MVCApp.Models.SortedDataModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>
<div>
    <h4>SortedDataModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SortedNumberSequence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SortedNumberSequence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SortType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SortType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeElapsed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeElapsed)
        </dd>
    </dl>
    
    <a asp-action="ViewSequences">Back to List</a>
</div>

MVCApp/MVCApp/Views/NumberSequences/Index.cshtml
@model FormNumberInputModel

@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1>Enter a number!</h1>
    <form asp-action="SubmitNumber">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input asp-for="CurrentNumber"/>
        </div>
        <br>
        <span asp-validation-for="CurrentNumber" class="text-danger"></span>
        <div class="form-group">
            <input type="submit" value="Add Number" class="btn btn-primary"/>
        </div>
    </form>
    <div>
        <br>
        <h2>Entered Numbers: </h2>
        <div>
            @if (Context.Request.Cookies.TryGetValue("NumberCookie", out var cookieValue))
            {
                <h3>@cookieValue</h3>
            }
        </div>
    </div>
    <br>
    <form asp-controller="NumberSequences" asp-action="SubmitAll" method="post">
        <h2>Sort Type:</h2>
        <select asp-for="SortType">
            <option value="Ascending">Ascending</option>
            <option value="Descending">Descending</option>
        </select>
        <br>
        <br>
        <br>
        <div class="form-group">
            <input type="submit" value="Submit Sequence" class="btn btn-primary"/>
        </div>
    </form>
    <div>
        @if (ViewBag.Message == "Submission Successful")
        {
            <p style="color:green;">@ViewBag.Message</p>
        }
        else
        {
            <p style="color:red;">@ViewBag.Message</p>
        }
        
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCApp/MVCApp/Views/NumberSequences/ViewSequences.cshtml
@model IEnumerable<MVCApp.Models.SortedDataModel>

@{
    ViewBag.Title = "Sequences";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <title>
        Sequences
    </title>
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
</head>

<form asp-action="ViewSequences" method="get">
    <div class="form-actions no-color">
        <p>
            Find by number: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="ViewSequences">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SortedNumberSequence)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SortType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeElapsed)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SortedNumberSequence)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SortType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeElapsed)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id"><i class="las la-info-circle  la-2x"></i></a>
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.Id"><i class="las la-trash-alt  la-2x"></i></a>
            </td>
        </tr>
    }
    </tbody>
</table>

<p>
    <a asp-action="ExportAllSequences">Export All Sequences</a>
    <a asp-action="ViewSequences" asp-route-sortType="Ascending" asp-route-searchString=@ViewData["CurrentFilter"]>Sort By Time Elapsed Ascending</a>
    <a asp-action="ViewSequences" asp-route-sortType="Descending" asp-route-searchString=@ViewData["CurrentFilter"]>Sort By Time Elapsed Descending</a>
</p>

<p style="color:red;">@ViewBag.Message</p>

MVCApp/MVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TechnicalTestIshverpalToor.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="NumberSequences" asp-action="Index">MVCApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NumberSequences" asp-action="Index">Enter Sequence</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="NumberSequences" asp-action="ViewSequences">View Sequences</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - MVCApp
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>